
build:
	@scripts/make-build.sh node-typescript

publish: tag-latest
	@scripts/make-publish.sh node-typescript

dev:
	@scripts/make-dev.sh node-typescript

dev-debug:
	@scripts/make-dev-debug.sh node-typescript

run: 
	@scripts/make-run.sh node-typescript

run-debug: 
	@scripts/make-run-debug.sh node-typescript

sh:
	@scripts/make-sh.sh node-typescript

tag-latest: 
	@scripts/make-tag-latest.sh node-typescript

tag-version:
	@scripts/make-tag-version.sh node-typescript